# Generated by Django 4.2.7 on 2023-12-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating_yellow', models.FloatField(default=72.0)),
                ('rating_white', models.FloatField(default=72.0)),
                ('rating_gold', models.FloatField(default=72.0)),
                ('rating_red', models.FloatField(default=72.0)),
                ('rating_blue', models.FloatField(default=72.0)),
                ('record_mens', models.IntegerField(default='NULL')),
                ('record_ladies', models.IntegerField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='TeeTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='tee off time')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no_1', models.CharField(max_length=6)),
                ('member_no_2', models.CharField(max_length=6)),
                ('member_no_3', models.CharField(max_length=6)),
                ('member_no_4', models.CharField(max_length=6)),
                ('play_date', models.DateField(verbose_name='date to play')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randpark.course')),
                ('tee_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randpark.teetimes')),
            ],
        ),
    ]
